//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCharacterFriend
    {
        public int Id { get; set; }
        public int FriendID { get; set; }
        public string FriendName { get; set; }
        public int Level { get; set; }
        public int Class { get; set; }
        public int TCharacterID { get; set; }
    
        public virtual TCharacter Owner { get; set; }
    }
}
