//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCharacterItem
    {
        public int ID { get; set; }
        public int ItemID { get; set; }
        public int ItemCount { get; set; }
        public int CharacterID { get; set; }
    
        public virtual TCharacter Owner { get; set; }
    }
}
