//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGuildMember
    {
        public int Id { get; set; }
        public int CharacterId { get; set; }
        public string Name { get; set; }
        public int Class { get; set; }
        public int Level { get; set; }
        public int Title { get; set; }
        public System.DateTime JoinTime { get; set; }
        public System.DateTime LastOnlineTime { get; set; }
        public int GuildId { get; set; }
    
        public virtual TGuild Guild { get; set; }
    }
}
