//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGuild
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TGuild()
        {
            this.GuildMembers = new HashSet<TGuildMember>();
            this.GuildApplicants = new HashSet<TGuildApplicant>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int LeaderId { get; set; }
        public string LeaderName { get; set; }
        public string Overview { get; set; }
        public System.DateTime FoundTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TGuildMember> GuildMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TGuildApplicant> GuildApplicants { get; set; }
    }
}
